package com.youcode.reservationApp.entities;

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReservationLimit generated by hbm2java
 */
@Entity
@Table(name = "reservation_limit")
public class ReservationLimit implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	@Basic
	@Temporal(TemporalType.DATE)
	private Date date;
	@Column(name = "reservation_limit")
	private int reservationLimit;
	private String type;

	public ReservationLimit() {
	}

	public ReservationLimit(Date date, int reservationLimit) {
		this.date = date;
		this.reservationLimit = reservationLimit;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public int getReservationLimit() {
		return this.reservationLimit;
	}

	public void setReservationLimit(int reservationLimit) {
		this.reservationLimit = reservationLimit;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
	
	

}
