package com.youcode.reservationApp.entities;

import java.util.Date;

/**
 * ReservationLimit generated by hbm2java
 */
public class ReservationLimit implements java.io.Serializable {

	private Long id;
	private Date date;
	private int reservationLimit;

	public ReservationLimit() {
	}

	public ReservationLimit(Date date, int reservationLimit) {
		this.date = date;
		this.reservationLimit = reservationLimit;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public int getReservationLimit() {
		return this.reservationLimit;
	}

	public void setReservationLimit(int reservationLimit) {
		this.reservationLimit = reservationLimit;
	}

}
