package com.youcode.reservationApp.entities;
// default package
// Generated Mar 12, 2021, 10:08:26 AM by Hibernate Tools 5.4.27.Final

import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Roles generated by hbm2java
 */
@Entity
public class Roles implements java.io.Serializable {

	@Id
	private Long id;
	private String title;

	public Roles() {
	}

	public Roles(String title) {
		this.title = title;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
