package com.youcode.reservationApp.entities;
// default package
// Generated Mar 12, 2021, 10:08:26 AM by Hibernate Tools 5.4.27.Final

/**
 * Roles generated by hbm2java
 */
public class Roles implements java.io.Serializable {

	private Integer id;
	private String title;

	public Roles() {
	}

	public Roles(String title) {
		this.title = title;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
