package com.youcode.reservationApp.entity;
// default package
// Generated Mar 10, 2021, 10:39:38 PM by Hibernate Tools 5.4.27.Final

import java.util.Date;

/**
 * ReservationLimitId generated by hbm2java
 */
public class ReservationLimit implements java.io.Serializable {

	private Date date;
	private int reservationLimit;

	public ReservationLimit() {
	}

	public ReservationLimit(Date date, int reservationLimit) {
		this.date = date;
		this.reservationLimit = reservationLimit;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public int getReservationLimit() {
		return this.reservationLimit;
	}

	public void setReservationLimit(int reservationLimit) {
		this.reservationLimit = reservationLimit;
	}

	

}
