  package com.youcode.reservationApp.entity;
// default package
// Generated Mar 10, 2021, 10:39:38 PM by Hibernate Tools 5.4.27.Final

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Long id;
	private String name;
	private String email;
	private String password;
	private String role;
	private String state;

	public Users() {
	}

	public Users(String name, String email, String password, String role, String state) {
		this.name = name;
		this.email = email;
		this.password = password;
		this.role = role;
		this.state = state;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
